export const credentialTemplate = {
  $schema: "http://json-schema.org/draft-07/schema#",
  type: "object",
  title: "AI Interaction Credential",
  description: "A credential representing an interaction with an AI model",
  properties: {
    modelInfo: {
      type: "object",
      required: ["name", "version", "provider"],
      properties: {
        name: {
          type: "string",
          description: "Name of the AI model"
        },
        version: {
          type: "string",
          description: "Version of the AI model"
        },
        provider: {
          type: "string",
          description: "Provider of the AI model"
        }
      }
    },
    input: {
      type: "object",
      required: ["prompt", "timestamp"],
      properties: {
        prompt: {
          type: "string",
          description: "The input prompt provided to the AI model"
        },
        timestamp: {
          type: "string",
          format: "date-time",
          description: "ISO timestamp when the input was provided"
        }
      }
    },
    output: {
      type: "object",
      required: ["response", "timestamp"],
      properties: {
        response: {
          type: "string",
          description: "The response generated by the AI model"
        },
        timestamp: {
          type: "string",
          format: "date-time",
          description: "ISO timestamp when the output was generated"
        }
      }
    }
  },
  required: ["modelInfo", "input", "output"]
};
